--liquibase formatted sql

--changeset uijin:V001-01-create-brand
--comment: 브랜드. 모든 운영 데이터가 이 값을 기준으로 격리된다.
CREATE TABLE brand (
    id         NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR2(20)  NOT NULL,
    name       VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
--rollback DROP TABLE brand;

--changeset uijin:V001-02-brand-code-unique
--comment: 브랜드 코드는 조회 키로 쓰이므로 중복을 막는다.
ALTER TABLE brand ADD CONSTRAINT uk_brand_code UNIQUE (code);
--rollback ALTER TABLE brand DROP CONSTRAINT uk_brand_code;
