--liquibase formatted sql

--changeset uijin:V003-01-create-influencer
--comment: 인플루언서. 삭제 대신 status 를 바꾼다. follower_total 은 채널 팔로워 합계의 비정규화 컬럼이다.
CREATE TABLE influencer (
    id               NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(50)   NOT NULL,
    category         VARCHAR2(20)   NOT NULL,
    affiliation_type VARCHAR2(20)   NOT NULL,
    agency_name      VARCHAR2(100),
    memo             VARCHAR2(1000),
    status           VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    follower_total   NUMBER(19)     DEFAULT 0 NOT NULL,
    created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);
--rollback DROP TABLE influencer;

--changeset uijin:V003-02-create-influencer-channel
--comment: 인플루언서 채널. 한 사람이 인스타그램과 유튜브를 함께 운영하므로 1:N 이다. 성과 스냅샷이 채널을 참조하므로 삭제 대신 status 를 바꾼다.
CREATE TABLE influencer_channel (
    id                 NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    influencer_id      NUMBER(19)    NOT NULL,
    platform           VARCHAR2(20)  NOT NULL,
    channel_identifier VARCHAR2(100) NOT NULL,
    follower_count     NUMBER(19)    DEFAULT 0 NOT NULL,
    status             VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    created_at         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_channel_influencer FOREIGN KEY (influencer_id) REFERENCES influencer (id)
);
--rollback DROP TABLE influencer_channel;

--changeset uijin:V003-03-channel-identifier-unique
--comment: 같은 플랫폼의 같은 채널이 두 인플루언서에 등록되는 것을 막는다.
ALTER TABLE influencer_channel ADD CONSTRAINT uk_channel_platform_identifier UNIQUE (platform, channel_identifier);
--rollback ALTER TABLE influencer_channel DROP CONSTRAINT uk_channel_platform_identifier;

--changeset uijin:V003-04-channel-influencer-index
--comment: 상세 조회가 인플루언서 하나의 채널을 모두 읽는다. Oracle 은 외래 키 컬럼에 인덱스를 자동 생성하지 않는다.
CREATE INDEX ix_channel_influencer ON influencer_channel (influencer_id);
--rollback DROP INDEX ix_channel_influencer;
